### ISSUE TITLE
Backup/Restore Specific Collections

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/app-dump#1]
My application have many branches office, so I would like to backup with some collections and some documents that related with one branch.
Pl help me.

**Comment by IstoraMandiri** [comment]
Thanks for the suggestion. Shouldn't be too hard to implement, but I don't have plans for it at the moment - I may get around to it should I need it myself. 

Feel free to send a PR.

**Comment by thearabbit** [comment]
Excuse me, Could you explain me for do this?

**Comment by hex7c0** [comment]
"specific collections" is available on mongo-(backup|restore) package

[mongodb-backup example](https://github.com/hex7c0/mongodb-backup/blob/master/examples/collection.js#L22)

**Comment by IstoraMandiri** [comment]
Pinging @elosoman, who forked this:

https://github.com/compoundtherapy/app-dump/commit/94cc56ad2ffc02d1052d7fd71d4b63a2626546bc

Is this usable? Can I merge it?

**Comment by IstoraMandiri** [comment]
Implemented in v 0.2
