### ISSUE TITLE
iron:router dependency

### ISSUE THREAD

**Issue by virgotopia** [hitchcott/app-dump#11]
Hello,
Would you consider removing iron-router dependency?
I have a project where I use Flow-router and including your package brings everything down because of conflicts between the two routers.
Any thoughts?

**Comment by virgotopia** [comment]
Well, let me dig more into this because I tried the Flow-router and app-dump on a simpler app and I have no conflict.
Sorry for the noise, I close the issue until I found something relevant.

**Comment by virgotopia** [comment]
Well, let me dig more into this because I tried the Flow-router and app-dump on a simpler app and I have no conflict.
Sorry for the noise, I close the issue until I found something relevant.

**Comment by virgotopia** [comment]
Well, let me dig more into this because I tried the Flow-router and app-dump on a simpler app and I have no conflict.
Sorry for the noise, I close the issue until I found something relevant.

**Comment by virgotopia** [comment]
Well, let me dig more into this because I tried the Flow-router and app-dump on a simpler app and I have no conflict.
Sorry for the noise, I close the issue until I found something relevant.

**Comment by virgotopia** [comment]
Well, let me dig more into this because I tried the Flow-router and app-dump on a simpler app and I have no conflict.
Sorry for the noise, I close the issue until I found something relevant.

**Comment by IstoraMandiri** [comment]
No problem -- yeah, IR is only used for serving the RESTful endpoint; not for actual routing.

Let me know if you have any compatibility issues!
