### ISSUE TITLE
Is it possible to use "Meteor method with transport ajax" instead of "Router"?

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/app-dump#16]
Excuse me, Is it possible to use `Meteor method` with `transport ajax` instead of `Router` to down/up?

``` js
...............
ajax: {
            data: function (params) {
                return params;
            },
            transport: function (args) {
                // Meteor method call
                Meteor.call('methodUp_Down', args.data, function (err, results) {
                    if (err) {
                        args.error(err);
                        return;
                    }

                    args.success(results);
                });
            },
            results:...........

```

What do you think?

**Comment by IstoraMandiri** [comment]
Sounds interesting but I'm a little confused -- what are the pros/cons over the current implementation?

Are you using DDP instead of REST, or as well as?

It'd be great to see an example or PR!

**Comment by thearabbit** [comment]
I am not sure, I think that it is good if don't use router.

**Comment by IstoraMandiri** [comment]
Hi, thanks for contributing @thearabbit but I will close this issue for now.

Please let me know if there is a genuine advantage and I will reopen it.

Thanks!
