### ISSUE TITLE
Could don't show the new windows for backup (download directly on the same page)?

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/app-dump#19]
Could don't show the new windows for backup (download directly on the same page)?

**Comment by IstoraMandiri** [comment]
The reason I'm not doing that right now is that the app state might get lost if there is an error returned -- it would redirect you to a different page and then when you press back it would reload everything. Opening a new tab avoids this and is not super pretty but, not that bad.

Moreover, Chrome will close that tab automatically - what is your browser?

Anyway this is perhaps a good reason to find a better way, perhaps using AJAX, so I'll look into it and see if there's anything I can do.

As always, if you feel like doing a Pull Request please do!

**Comment by thearabbit** [comment]
I use `Chrome`, but don't auto close.
Excuse me, I don't have more experience for this.
But I use to try the `netanelgilad:excel` with demo to create excel file and download directly.
(netanelgilad:node-uuid, netanelgilad:mkdirp, vsivsi:file-collection)
