### ISSUE TITLE
deps: version pulled out bson@0.4.11

### ISSUE THREAD

**Issue by hex7c0** [hitchcott/app-dump#24]
please update your mongodb-backup and mongodb-restore to next release `1.4.2`
I'll release today

https://github.com/hex7c0/mongodb-backup/issues/5
https://github.com/hex7c0/mongodb-restore/issues/4

**Comment by thearabbit** [comment]
I tried in my local package `1.4.2`, but don't work.

**Comment by IstoraMandiri** [comment]
Thanks to @msand , fixed in `0.4.2`
