### ISSUE TITLE
Wrong Busboy name

### ISSUE THREAD

**Issue by hculap** [hitchcott/app-dump#3]
Hi!

There is a problem with busyboy on Linux systems. 
In file `"app-dump-server.coffee"` line 4:

`Busboy = Npm.require("Busboy")`

but you should change it to:

`Busboy = Npm.require("busboy")`
so busyboy should be downcase. For OS X and Windows problem not exists because file system is case insensitive, this issue exists only on Linux.

**Comment by IstoraMandiri** [comment]
Good catch @hculap. I admit I hadn't tested on anything other than OSX.

I've added your fix commit to the branch so you're now listed as contributor :clap:

Cheers!
