### ISSUE TITLE
Error I intent dowload backup Meteor.userId can only be invoked in method calls

### ISSUE THREAD

**Issue by wzalazar** [hitchcott/app-dump#9]
Hi, I try to use this package and when I want to download the backup the application triggers this error.
Sincerely, I don't know why, I wish any help, thanks

Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions. at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1) at Object.Meteor.user (packages/accounts-base/accounts_server.js:24:1) at [object Object].IR_Filters.mustBeSignedIn (app/__app/router/router.js:49:22) at packages/iron:router/lib/router.js:277:1 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1) at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1) at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1) at packages/meteor/dynamics_nodejs.js:121:1 at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)

**Comment by Khalid545** [comment]
Hi,

For anyone having the same issue, you need to add 'appDumpHTTP' the route used by the package to the exceptions list of any iron-router hook you use to check current user.

``` javascript
Router.onBeforeAction(IR_Filters.mustBeSignedIn, {
  except: ['appDumpHTTP']
});
```

**Comment by IstoraMandiri** [comment]
Thanks @Khalid545, i'll add this to the readme.
